custom:
  schedule:
    production: true
    staging: false

  jetpack:
    trace:
      allowMissing:
        node-fetch:
          - encoding
      ignores:
        - aws-sdk

functions:
  createTable:
    handler: dist/handlers/createTable.handler

  exportStories:
    handler: dist/handlers/exportStories.handler

  saveStories:
    events:
      # 毎日00:01（JST）に更新します。Lambda の実行環境が UTC なので15:01（UTC）に設定。
      - schedule:
        rate: cron(1 15 * * * *)
        enabled: enabled: ${self:custom.schedule.${opt:stage}}
    handler: dist/handlers/saveStories.handler

package:
  exclude:
    - dist/tsconfig.tsbuildinfo
    - node_modules/aws-sdk/**
    - s3/**
    - src/**
    - .prettierignore
    - .prettierrc.json
    - package-lock.json
    - package.json
    - tsconfig.json
    - tsconfig.tsbuildinfo
    - LICENSE
    - README.md

plugins:
  - serverless-jetpack

provider:
  environment:
    DYNAMO_DB_TABLE_NAME: ${ssm:/hacker-mainichi/${opt:stage}/DYNAMO_DB_TABLE_NAME}
    NODE_OPTIONS: --enable-source-maps
    S3_DATA_BUCKET_NAME: ${ssm:/hacker-mainichi/${opt:stage}/S3_DATA_BUCKET_NAME}
    TZ: Asia/Tokyo
  lambdaHashingVersion: 20201221
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  timeout: 900

service: hacker-mainichi
